name: CI # Workflow 的名称

on: # 触发 Workflow 运行的事件条件
  push: # 当有推送事件发生时触发
    branches: [master] # 只有在 master 分支上的推送事件触发
  pull_request: # 当有拉取请求事件发生时触发
    branches: [master] # 只有在 master 分支上的拉取请求事件触发
  workflow_dispatch: # 允许手动触发此 Workflow

jobs:
  build: # Workflow 中的一个 job，名为 "build"
    runs-on: ubuntu-latest # 运行环境为最新版的 Ubuntu

    steps: # 此 job 的一系列步骤
      - uses: actions/checkout@v2 # 检出代码仓库到 $GITHUB_WORKSPACE 下，以使 job 可以访问代码

      - name: Build And Push Docker image # 步骤名称，用于构建和推送 Docker 镜像
        env: # 步骤运行时使用的环境变量
          #docker_repo: registry.cn-shenzhen.aliyuncs.com/devan # 指定镜像仓库地址
          docker_repo: git@github.com:zfwV/111.git
          image_name: daxigua # 指定镜像名称
          tag: latest # 指定镜像标签
        run: | # 运行的命令
          docker version # 查看 Docker 版本
          docker login --username=VVzfw --password=zfw637313 registry.cn-shenzhen.aliyuncs.com # 登录阿里云镜像仓库
          docker build . --file Dockerfile --tag $docker_repo
